/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>


__attribute__((visibility("hidden")))
@interface AboutViewController : UIViewController {
}
-(?)backButtonPushed:(?)pushed;
-(?)didReceiveMemoryWarning;
-(?)viewWillAppear:(?)view;
-(?)viewDidLoad;
-(?)loadView;
-(?)dealloc;
@end

