/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIButton.h>


__attribute__((visibility("hidden")))
@interface AdView : UIButton {
@private
	? background;
	? iconImage;
	? title;
	? subTitle;
	? titleFont;
	? subTitleFont;
	? titleColor;
	? subTitleColor;
}
@property(assign) ? XXEncryptedProperty_3ee32;
@property(assign) ? XXEncryptedProperty_3f080;
@property(assign) ? XXEncryptedProperty_3ee28;
-(?)setSubTitle:(?)title;
-(?)subTitle;
-(?)setTitle:(?)title;
-(?)title;
-(?)setIconImage:(?)image;
-(?)iconImage;
-(?)dealloc;
-(?)drawRect:(?)rect;
-(?)init;
@end

