/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ASIAutorotatingViewController.h"
#import "XXEncryptedProtocol_545f8.h"
#import "XXEncryptedProtocol_544dc.h"
#import "XXEncryptedProtocol_54504.h"


__attribute__((visibility("hidden")))
@interface ASIAuthenticationDialog : ASIAutorotatingViewController <XXEncryptedProtocol_545f8, XXEncryptedProtocol_544dc, XXEncryptedProtocol_54504> {
@private
	? request;
	? type;
	? tableView;
	? presentingController;
	? didEnableRotationNotifications;
}
@property(assign) ? XXEncryptedProperty_44058;
@property(assign) ? XXEncryptedProperty_44014;
@property(assign) ? XXEncryptedProperty_43fd2;
@property(assign) ? XXEncryptedProperty_43fc4;
@property(assign) ? XXEncryptedProperty_3df08;
+(?)dismiss;
+(?)presentAuthenticationDialogForRequest:(?)request;
+(?)initialize;
-(?)setPresentingController:(?)controller;
-(?)setDidEnableRotationNotifications:(?)enableRotationNotifications;
-(?)didEnableRotationNotifications;
-(?)setTableView:(?)view;
-(?)tableView;
-(?)setType:(?)type;
-(?)type;
-(?)setRequest:(?)request;
-(?)request;
-(?)tableView:(?)view titleForFooterInSection:(?)section;
-(?)tableView:(?)view numberOfRowsInSection:(?)section;
-(?)tableView:(?)view cellForRowAtIndexPath:(?)indexPath;
-(?)tableView:(?)view titleForHeaderInSection:(?)section;
-(?)tableView:(?)view heightForHeaderInSection:(?)section;
-(?)tableView:(?)view heightForFooterInSection:(?)section;
-(?)numberOfSectionsInTableView:(?)tableView;
-(?)loginWithCredentialsFromDialog:(?)dialog;
-(?)presentNextDialog;
-(?)requestsRequiringTheseCredentials;
-(?)cancelAuthenticationFromDialog:(?)dialog;
-(?)show;
-(?)showTitle;
-(?)dismiss;
-(?)viewDidDisappear:(?)view;
-(?)domainField;
-(?)passwordField;
-(?)usernameField;
-(?)textFieldInRow:(?)row section:(?)section;
-(?)presentingController;
-(?)orientationChanged:(?)changed;
-(?)keyboardWillShow:(?)keyboard;
-(?)dealloc;
-(?)init;
@end

