/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "XXEncryptedProtocol_546a8.h"


__attribute__((visibility("hidden")))
@interface ASIDownloadCache : NSObject <XXEncryptedProtocol_546a8> {
@private
	? defaultCachePolicy;
	? storagePath;
	? accessLock;
	? shouldRespectCacheControlHeaders;
}
@property(assign) ? XXEncryptedProperty_493ac;
@property(assign) ? XXEncryptedProperty_49224;
@property(assign) ? XXEncryptedProperty_493fc;
@property(assign) ? XXEncryptedProperty_451b2;
+(?)rfc1123DateFormatter;
+(?)keyForRequest:(?)request;
+(?)serverAllowsResponseCachingForRequest:(?)request;
+(?)sharedCache;
-(?)setShouldRespectCacheControlHeaders:(?)respectCacheControlHeaders;
-(?)shouldRespectCacheControlHeaders;
-(?)setAccessLock:(?)lock;
-(?)accessLock;
-(?)clearCachedResponsesForStoragePolicy:(?)storagePolicy;
-(?)setDefaultCachePolicy:(?)policy;
-(?)defaultCachePolicy;
-(?)isCachedDataCurrentForRequest:(?)request;
-(?)removeCachedDataForRequest:(?)request;
-(?)pathToCachedResponseDataForRequest:(?)request;
-(?)cachedResponseDataForRequest:(?)request;
-(?)cachedHeadersForRequest:(?)request;
-(?)storeResponseForRequest:(?)request maxAge:(?)age;
-(?)setStoragePath:(?)path;
-(?)storagePath;
-(?)dealloc;
-(?)init;
@end

