/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_54620.h"
#import "ASIHTTPRequest.h"


__attribute__((visibility("hidden")))
@interface ASIFormDataRequest : ASIHTTPRequest <XXEncryptedProtocol_54620> {
@private
	? postData;
	? fileData;
	? postFormat;
	? stringEncoding;
}
@property(assign) ? XXEncryptedProperty_44335;
@property(assign) ? XXEncryptedProperty_44280;
@property(assign) ? XXEncryptedProperty_4422f;
@property(assign) ? XXEncryptedProperty_44486;
+(?)requestWithURL:(?)url;
-(?)setStringEncoding:(?)encoding;
-(?)stringEncoding;
-(?)setPostFormat:(?)format;
-(?)postFormat;
-(?)setFileData:(?)data;
-(?)fileData;
-(?)setPostData:(?)data;
-(?)postData;
-(?)copyWithZone:(?)zone;
-(?)appendPostString:(?)string;
-(?)buildURLEncodedPostBody;
-(?)buildMultipartFormDataPostBody;
-(?)buildPostBody;
-(?)setData:(?)data withFileName:(?)fileName andContentType:(?)type forKey:(?)key;
-(?)setData:(?)data forKey:(?)key;
-(?)addData:(?)data withFileName:(?)fileName andContentType:(?)type forKey:(?)key;
-(?)addData:(?)data forKey:(?)key;
-(?)setFile:(?)file withFileName:(?)fileName andContentType:(?)type forKey:(?)key;
-(?)setFile:(?)file forKey:(?)key;
-(?)addFile:(?)file withFileName:(?)fileName andContentType:(?)type forKey:(?)key;
-(?)addFile:(?)file forKey:(?)key;
-(?)setPostValue:(?)value forKey:(?)key;
-(?)addPostValue:(?)value forKey:(?)key;
-(?)dealloc;
-(?)initWithURL:(?)url;
-(?)encodeURL:(?)url;
@end

