/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface ASIInputStream : NSObject {
@private
	? stream;
	? request;
}
@property(assign) ? XXEncryptedProperty_3df08;
@property(assign) ? XXEncryptedProperty_441be;
+(?)inputStreamWithData:(?)data request:(?)request;
+(?)inputStreamWithFileAtPath:(?)path request:(?)request;
+(?)initialize;
-(?)setRequest:(?)request;
-(?)request;
-(?)setStream:(?)stream;
-(?)stream;
-(?)forwardInvocation:(?)invocation;
-(?)methodSignatureForSelector:(?)selector;
-(?)streamError;
-(?)streamStatus;
-(?)setProperty:(?)property forKey:(?)key;
-(?)propertyForKey:(?)key;
-(?)removeFromRunLoop:(?)runLoop forMode:(?)mode;
-(?)scheduleInRunLoop:(?)runLoop forMode:(?)mode;
-(?)setDelegate:(?)delegate;
-(?)delegate;
-(?)close;
-(?)open;
-(?)read:(?)read maxLength:(?)length;
-(?)dealloc;
@end

