/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_54620.h"
#import "XXEncryptedProtocol_54658.h"
#import "XXEncryptedProtocol_54680.h"
#import <Foundation/NSOperationQueue.h>


__attribute__((visibility("hidden")))
@interface ASINetworkQueue : NSOperationQueue <XXEncryptedProtocol_54658, XXEncryptedProtocol_54680, XXEncryptedProtocol_54620> {
@private
	? delegate;
	? requestDidStartSelector;
	? requestDidReceiveResponseHeadersSelector;
	? requestDidFinishSelector;
	? requestDidFailSelector;
	? queueDidFinishSelector;
	? uploadProgressDelegate;
	? bytesUploadedSoFar;
	? totalBytesToUpload;
	? downloadProgressDelegate;
	? bytesDownloadedSoFar;
	? totalBytesToDownload;
	? shouldCancelAllRequestsOnFailure;
	? requestsCount;
	? showAccurateProgress;
	? userInfo;
}
@property(assign) ? XXEncryptedProperty_48de8;
@property(assign) ? XXEncryptedProperty_48dca;
@property(assign) ? XXEncryptedProperty_48e25;
@property(assign) ? XXEncryptedProperty_48e0b;
@property(assign) ? XXEncryptedProperty_4819a;
@property(assign) ? XXEncryptedProperty_48c6e;
@property(assign) ? XXEncryptedProperty_4594a;
@property(assign) ? XXEncryptedProperty_3e67c;
@property(assign) ? XXEncryptedProperty_48da9;
@property(assign) ? XXEncryptedProperty_48d7b;
@property(assign) ? XXEncryptedProperty_48d92;
@property(assign) ? XXEncryptedProperty_48d62;
@property(assign) ? XXEncryptedProperty_48d39;
@property(assign) ? XXEncryptedProperty_48d1c;
@property(assign) ? XXEncryptedProperty_46b36;
@property(assign) ? XXEncryptedProperty_46b14;
+(?)queue;
-(?)setUserInfo:(?)info;
-(?)userInfo;
-(?)setShowAccurateProgress:(?)progress;
-(?)showAccurateProgress;
-(?)setDelegate:(?)delegate;
-(?)delegate;
-(?)setQueueDidFinishSelector:(?)finishSelector;
-(?)queueDidFinishSelector;
-(?)setRequestDidFailSelector:(?)failSelector;
-(?)requestDidFailSelector;
-(?)setRequestDidFinishSelector:(?)finishSelector;
-(?)requestDidFinishSelector;
-(?)setRequestDidReceiveResponseHeadersSelector:(?)receiveResponseHeadersSelector;
-(?)requestDidReceiveResponseHeadersSelector;
-(?)setRequestDidStartSelector:(?)startSelector;
-(?)requestDidStartSelector;
-(?)downloadProgressDelegate;
-(?)uploadProgressDelegate;
-(?)setShouldCancelAllRequestsOnFailure:(?)cancelAllRequestsOnFailure;
-(?)shouldCancelAllRequestsOnFailure;
-(?)setTotalBytesToDownload:(?)download;
-(?)totalBytesToDownload;
-(?)setBytesDownloadedSoFar:(?)far;
-(?)bytesDownloadedSoFar;
-(?)setTotalBytesToUpload:(?)upload;
-(?)totalBytesToUpload;
-(?)setBytesUploadedSoFar:(?)far;
-(?)bytesUploadedSoFar;
-(?)setRequestsCount:(?)count;
-(?)requestsCount;
-(?)copyWithZone:(?)zone;
-(?)respondsToSelector:(?)selector;
-(?)proxyAuthenticationNeededForRequest:(?)request;
-(?)authenticationNeededForRequest:(?)request;
-(?)request:(?)request incrementUploadSizeBy:(?)by;
-(?)request:(?)request incrementDownloadSizeBy:(?)by;
-(?)request:(?)request didSendBytes:(?)bytes;
-(?)request:(?)request didReceiveBytes:(?)bytes;
-(?)requestFailed:(?)failed;
-(?)requestFinished:(?)finished;
-(?)requestReceivedResponseHeaders:(?)headers;
-(?)requestStarted:(?)started;
-(?)addOperation:(?)operation;
-(?)addHEADOperation:(?)operation;
-(?)resetProgressDelegate:(?)delegate;
-(?)setDownloadProgressDelegate:(?)delegate;
-(?)setUploadProgressDelegate:(?)delegate;
-(?)cancelAllOperations;
-(?)go;
-(?)reset;
-(?)setSuspended:(?)suspended;
-(?)dealloc;
-(?)init;
@end

