/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewController.h>


__attribute__((visibility("hidden")))
@interface AutocompleteCharsOptionViewController : UITableViewController {
}
-(?)tableView:(?)view didSelectRowAtIndexPath:(?)indexPath;
-(?)tableView:(?)view cellForRowAtIndexPath:(?)indexPath;
-(?)tableView:(?)view numberOfRowsInSection:(?)section;
-(?)numberOfSectionsInTableView:(?)tableView;
-(?)backButtonPushed:(?)pushed;
-(?)viewDidLoad;
-(?)dealloc;
@end

