/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>


__attribute__((visibility("hidden")))
@interface BlockView : UIView {
@private
	? delegate;
}
@property(assign) ? XXEncryptedProperty_3e67c;
-(?)setDelegate:(?)delegate;
-(?)delegate;
-(?)touchesEnded:(?)ended withEvent:(?)event;
@end

