/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_54464.h"
#import "XXEncryptedProtocol_5448c.h"
#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface EOWAppDelegate : NSObject <XXEncryptedProtocol_54464, XXEncryptedProtocol_5448c> {
@private
	? window;
	? tabBarController;
	? tabBar;
	? internetReach;
	? callbackURL;
	? callbackButtonView;
	? alert;
}
@property(assign) ? XXEncryptedProperty_3d4e2;
@property(assign) ? XXEncryptedProperty_3d3b3;
@property(assign) ? XXEncryptedProperty_3d3a5;
@property(assign) ? XXEncryptedProperty_3d39e;
@property(assign) ? XXEncryptedProperty_3fa18;
@property(assign) ? XXEncryptedProperty_3d38b;
-(?)setCallbackButtonView:(?)view;
-(?)callbackButtonView;
-(?)setCallbackURL:(?)url;
-(?)callbackURL;
-(?)setInternetReach:(?)reach;
-(?)internetReach;
-(?)tabBar;
-(?)setTabBarController:(?)controller;
-(?)tabBarController;
-(?)setWindow:(?)window;
-(?)window;
-(?)backToCallerApplication:(?)callerApplication;
-(?)alertView:(?)view clickedButtonAtIndex:(?)index;
-(?)dealloc;
-(?)application:(?)application handleOpenURL:(?)url;
-(?)applicationWillEnterForeground:(?)application;
-(?)applicationDidEnterBackground:(?)application;
-(?)applicationWillTerminate:(?)application;
-(?)application:(?)application didFinishLaunchingWithOptions:(?)options;
-(?)setupCalbackButton:(?)button;
-(?)saveSettings;
@end

