/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_5457c.h"
#import <UIKit/UIViewController.h>


__attribute__((visibility("hidden")))
@interface HelpViewController : UIViewController <XXEncryptedProtocol_5457c> {
@private
	? helpWebView;
	? titleView;
	? pageURL;
}
@property(assign) ? XXEncryptedProperty_4247c;
-(?)setPageURL:(?)url;
-(?)pageURL;
-(?)backButtonPushed:(?)pushed;
-(?)webView:(?)view shouldStartLoadWithRequest:(?)request navigationType:(?)type;
-(?)webView:(?)view didFailLoadWithError:(?)error;
-(?)webViewDidFinishLoad:(?)webView;
-(?)webViewDidStartLoad:(?)webView;
-(?)didReceiveMemoryWarning;
-(?)viewDidLoad;
-(?)loadView;
-(?)dealloc;
@end

