/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_5457c.h"
#import <UIKit/UIViewController.h>


__attribute__((visibility("hidden")))
@interface HomeViewController : UIViewController <XXEncryptedProtocol_5457c> {
@private
	? homeView;
	? loadingView;
	? indicator;
	? scrollView;
	? ads;
	? affiliateURL;
	? iTunesURL;
	? searchViewController;
	? alert;
}
@property(assign) ? XXEncryptedProperty_42490;
@property(assign) ? XXEncryptedProperty_41dd2;
@property(assign) ? XXEncryptedProperty_3ec50;
@property(assign) ? XXEncryptedProperty_3ec30;
@property(assign) ? XXEncryptedProperty_41d64;
-(?)setSearchViewController:(?)controller;
-(?)searchViewController;
-(?)setITunesURL:(?)url;
-(?)iTunesURL;
-(?)setAffiliateURL:(?)url;
-(?)affiliateURL;
-(?)setAds:(?)ads;
-(?)ads;
-(?)scrollView;
-(?)applicationDidEnterBackground:(?)application;
-(?)applicationWillEnterForeground:(?)application;
-(?)tabBarControllerViewFrameChanged:(?)changed;
-(?)backButtonPushed:(?)pushed;
-(?)webView:(?)view didFailLoadWithError:(?)error;
-(?)webViewDidFinishLoad:(?)webView;
-(?)webView:(?)view shouldStartLoadWithRequest:(?)request navigationType:(?)type;
-(?)alertView:(?)view clickedButtonAtIndex:(?)index;
-(?)connectionDidFinishLoading:(?)connection;
-(?)connection:(?)connection willSendRequest:(?)request redirectResponse:(?)response;
-(?)openReferralURL:(?)url;
-(?)viewDidUnload;
-(?)didReceiveMemoryWarning;
-(?)viewWillAppear:(?)view;
-(?)viewDidLoad;
-(?)loadView;
-(?)dealloc;
@end

