/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface LaunchInfo : NSObject {
@private
	? action;
	? query;
	? callback;
	? bundleID;
	? sourceApplication;
	? URL;
	? params;
}
@property(assign) ? XXEncryptedProperty_433d4;
@property(assign) ? XXEncryptedProperty_460b2;
@property(assign) ? XXEncryptedProperty_3cdff;
@property(assign) ? XXEncryptedProperty_3f770;
@property(assign) ? XXEncryptedProperty_3cc6b;
@property(assign) ? XXEncryptedProperty_432a0;
@property(assign) ? XXEncryptedProperty_433cd;
+(?)sharedInstance;
-(?)setParams:(?)params;
-(?)params;
-(?)setURL:(?)url;
-(?)URL;
-(?)setSourceApplication:(?)application;
-(?)sourceApplication;
-(?)setBundleID:(?)anId;
-(?)bundleID;
-(?)setCallback:(?)callback;
-(?)callback;
-(?)setQuery:(?)query;
-(?)query;
-(?)setAction:(?)action;
-(?)action;
-(?)description;
-(?)dealloc;
@end

