/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSDictionary.h>


@interface NSDictionary (XMLParser)
-(?)childNodeByNodeName:(?)name;
-(?)attributeContentByName:(?)name;
-(?)childArray;
-(?)attributeArray;
-(?)nodeContent;
-(?)nodeName;
@end

@interface NSDictionary (L0URLParsing)
-(?)queryString;
@end

