/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>


__attribute__((visibility("hidden")))
@interface PopupViewController : UIViewController {
@private
	? selection;
	? viewController;
	? arrowUp;
	? arrowDown;
}
@property(assign) ? XXEncryptedProperty_4214a;
@property(assign) ? XXEncryptedProperty_42132;
+(?)sharedPopupViewController;
-(?)setViewController:(?)controller;
-(?)viewController;
-(?)setSelection:(?)selection;
-(?)selection;
-(?)mailButtonPushed:(?)pushed;
-(?)searchButtonPushed:(?)pushed;
-(?)copyButtonPushed:(?)pushed;
-(?)hidePopup;
-(?)showAtTargetRect:(?)targetRect inView:(?)view;
-(?)didReceiveMemoryWarning;
-(?)viewWillAppear:(?)view;
-(?)viewDidLoad;
-(?)loadView;
-(?)dealloc;
@end

