/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface Reachability : NSObject {
@private
	? key_;
	? reachabilityRef;
}
@property(assign) ? XXEncryptedProperty_442ae;
+(?)reachabilityForLocalWiFi;
+(?)reachabilityForInternetConnection;
+(?)reachabilityWithAddress:(?)address;
+(?)makeAddressKey:(?)key;
+(?)reachabilityWithHostName:(?)hostName;
+(?)accessInstanceVariablesDirectly;
-(?)setKey:(?)key;
-(?)key;
-(?)reachabilityFlags;
-(?)isReachableViaWiFi;
-(?)isReachableViaWWAN;
-(?)isInterventionRequired;
-(?)isConnectionOnDemand;
-(?)connectionRequired;
-(?)isConnectionRequired;
-(?)isReachable;
-(?)currentReachabilityStatus;
-(?)networkStatusForFlags:(?)flags;
-(?)isEqual:(?)equal;
-(?)stopNotifier;
-(?)startNotifier;
-(?)initWithReachabilityRef:(?)reachabilityRef;
-(?)dealloc;
@end

