/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_545cc.h"
#import "SBJsonBase.h"


__attribute__((visibility("hidden")))
@interface SBJsonWriter : SBJsonBase <XXEncryptedProtocol_545cc> {
@private
	? sortKeys;
	? humanReadable;
}
@property(assign) ? XXEncryptedProperty_43126;
@property(assign) ? XXEncryptedProperty_43238;
-(?)setHumanReadable:(?)readable;
-(?)humanReadable;
-(?)setSortKeys:(?)keys;
-(?)sortKeys;
-(?)appendString:(?)string into:(?)into;
-(?)appendDictionary:(?)dictionary into:(?)into;
-(?)appendArray:(?)array into:(?)into;
-(?)appendValue:(?)value into:(?)into;
-(?)indent;
-(?)stringWithObject:(?)object;
-(?)stringWithFragment:(?)fragment;
@end

