/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_545a4.h"
#import "XXEncryptedProtocol_545cc.h"
#import "SBJsonBase.h"


__attribute__((visibility("hidden")))
@interface SBJSON : SBJsonBase <XXEncryptedProtocol_545a4, XXEncryptedProtocol_545cc> {
@private
	? jsonParser;
	? jsonWriter;
}
@property(assign) ? XXEncryptedProperty_43126;
@property(assign) ? XXEncryptedProperty_43238;
-(?)setSortKeys:(?)keys;
-(?)sortKeys;
-(?)setHumanReadable:(?)readable;
-(?)humanReadable;
-(?)setMaxDepth:(?)depth;
-(?)maxDepth;
-(?)objectWithString:(?)string error:(?)error;
-(?)fragmentWithString:(?)string error:(?)error;
-(?)objectWithString:(?)string allowScalar:(?)scalar error:(?)error;
-(?)objectWithString:(?)string;
-(?)stringWithObject:(?)object error:(?)error;
-(?)stringWithFragment:(?)fragment error:(?)error;
-(?)stringWithObject:(?)object allowScalar:(?)scalar error:(?)error;
-(?)stringWithObject:(?)object;
-(?)dealloc;
-(?)init;
@end

