/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_545a4.h"
#import "SBJsonBase.h"


__attribute__((visibility("hidden")))
@interface SBJsonParser : SBJsonBase <XXEncryptedProtocol_545a4> {
@private
	? c;
}
+(?)initialize;
-(?)scanIsAtEnd;
-(?)scanNumber:(?)number;
-(?)scanHexQuad:(?)quad;
-(?)scanUnicodeChar:(?)aChar;
-(?)scanRestOfString:(?)string;
-(?)scanRestOfDictionary:(?)dictionary;
-(?)scanRestOfArray:(?)array;
-(?)scanRestOfNull:(?)null;
-(?)scanRestOfFalse:(?)aFalse;
-(?)scanRestOfTrue:(?)aTrue;
-(?)scanValue:(?)value;
-(?)objectWithString:(?)string;
-(?)fragmentWithString:(?)string;
@end

