/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface SBJsonBase : NSObject {
@private
	? errorTrace;
	? depth;
	? maxDepth;
}
@property(assign) ? XXEncryptedProperty_425fe;
@property(assign) ? XXEncryptedProperty_42860;
-(?)setMaxDepth:(?)depth;
-(?)maxDepth;
-(?)errorTrace;
-(?)clearErrorTrace;
-(?)addErrorWithCode:(?)code description:(?)description;
-(?)dealloc;
-(?)init;
@end

