/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_5457c.h"
#import <UIKit/UIViewController.h>


__attribute__((visibility("hidden")))
@interface SearchWebViewController : UIViewController <XXEncryptedProtocol_5457c> {
@private
	? searchWebView;
	? indicator;
	? titleView;
	? pageURL;
	? searchViewController;
}
@property(assign) ? XXEncryptedProperty_42490;
@property(assign) ? XXEncryptedProperty_4247c;
+(?)sharedWebViewController;
-(?)setSearchViewController:(?)controller;
-(?)searchViewController;
-(?)setPageURL:(?)url;
-(?)pageURL;
-(?)tabBarControllerViewFrameChanged:(?)changed;
-(?)backButtonPushed:(?)pushed;
-(?)webView:(?)view didFailLoadWithError:(?)error;
-(?)webViewDidFinishLoad:(?)webView;
-(?)webViewDidStartLoad:(?)webView;
-(?)webView:(?)view shouldStartLoadWithRequest:(?)request navigationType:(?)type;
-(?)viewDidUnload;
-(?)didReceiveMemoryWarning;
-(?)viewWillDisappear:(?)view;
-(?)viewWillAppear:(?)view;
-(?)viewDidLoad;
-(?)loadView;
-(?)dealloc;
@end

