/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_544dc.h"
#import "XXEncryptedProtocol_54504.h"
#import <UIKit/UIViewController.h>
#import "XXEncryptedProtocol_5452c.h"


__attribute__((visibility("hidden")))
@interface SearchViewController : UIViewController <XXEncryptedProtocol_544dc, XXEncryptedProtocol_54504, XXEncryptedProtocol_5452c> {
@private
	? searchTextField;
	? searchButton;
	? autoCompleteView;
	? blockView;
	? searchWord;
	? autoCompleteDictionary;
	? request;
	? homeViewController;
	? shouldNotCreateHomeViewController;
}
@property(assign) ? XXEncryptedProperty_3df23;
@property(assign) ? XXEncryptedProperty_3df10;
@property(assign) ? XXEncryptedProperty_3df08;
@property(assign) ? XXEncryptedProperty_40b9c;
@property(assign) ? XXEncryptedProperty_3d830;
-(?)setShouldNotCreateHomeViewController:(?)notCreateHomeViewController;
-(?)shouldNotCreateHomeViewController;
-(?)setHomeViewController:(?)controller;
-(?)homeViewController;
-(?)setRequest:(?)request;
-(?)request;
-(?)setAutoCompleteDictionary:(?)dictionary;
-(?)autoCompleteDictionary;
-(?)setSearchWord:(?)word;
-(?)searchWord;
-(?)tabBarControllerViewFrameChanged:(?)changed;
-(?)requestFailed:(?)failed;
-(?)requestFinished:(?)finished;
-(?)blockViewTapped:(?)tapped;
-(?)keyboardWillHide:(?)keyboard;
-(?)keyboardWillShow:(?)keyboard;
-(?)searchButtonPushed:(?)pushed;
-(?)searchWithURL:(?)url;
-(?)searchWithQuery:(?)query;
-(?)textFieldShouldReturn:(?)textField;
-(?)textFieldDidEndEditing:(?)textField;
-(?)textFieldEditingChanged:(?)changed;
-(?)tableView:(?)view didSelectRowAtIndexPath:(?)indexPath;
-(?)tableView:(?)view cellForRowAtIndexPath:(?)indexPath;
-(?)tableView:(?)view numberOfRowsInSection:(?)section;
-(?)numberOfSectionsInTableView:(?)tableView;
-(?)showHomeViewController;
-(?)viewDidUnload;
-(?)didReceiveMemoryWarning;
-(?)viewWillDisappear:(?)view;
-(?)viewWillAppear:(?)view;
-(?)viewDidLoad;
-(?)loadView;
-(?)dealloc;
@end

