/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITextField.h>


__attribute__((visibility("hidden")))
@interface SearchTextField : UITextField {
@private
	? searchMode;
	? searchModeView;
}
@property(assign) ? XXEncryptedProperty_41040;
-(?)searchMode;
-(?)setSearchMode:(?)mode;
-(?)modeChanged:(?)changed;
-(?)editingRectForBounds:(?)bounds;
-(?)textRectForBounds:(?)bounds;
-(?)leftViewRectForBounds:(?)bounds;
-(?)initWithFrame:(?)frame;
@end

