/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIWebView.h>


__attribute__((visibility("hidden")))
@interface SearchResultView : UIWebView {
@private
	? controller;
	? selection;
}
@property(assign) ? XXEncryptedProperty_42132;
@property(assign) ? XXEncryptedProperty_3f407;
-(?)setSelection:(?)selection;
-(?)selection;
-(?)setController:(?)controller;
-(?)controller;
-(?)mail:(?)mail;
-(?)search:(?)search;
-(?)copyText:(?)text;
-(?)showPopupMenu:(?)menu;
-(?)canPerformAction:(?)action withSender:(?)sender;
-(?)webviewGetSelection;
@end

