/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface SearchQuery : NSObject {
@private
	? searchWord;
	? page;
	? perfectMatch;
	? titleSearch;
	? searchResult;
	? URL;
}
@property(assign) ? XXEncryptedProperty_460b2;
@property(assign) ? XXEncryptedProperty_3f69d;
@property(assign) ? XXEncryptedProperty_3f73f;
@property(assign) ? XXEncryptedProperty_3f7cd;
@property(assign) ? XXEncryptedProperty_3f807;
@property(assign) ? XXEncryptedProperty_3d830;
-(?)setURL:(?)url;
-(?)URL;
-(?)setSearchResult:(?)result;
-(?)searchResult;
-(?)setTitleSearch:(?)search;
-(?)titleSearch;
-(?)setPerfectMatch:(?)match;
-(?)perfectMatch;
-(?)setPage:(?)page;
-(?)page;
-(?)setSearchWord:(?)word;
-(?)searchWord;
-(?)isEqual:(?)equal;
-(?)dealloc;
-(?)encodeWithCoder:(?)coder;
-(?)initWithCoder:(?)coder;
@end

