/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_54554.h"
#import "XXEncryptedProtocol_5457c.h"
#import "XXEncryptedProtocol_544dc.h"
#import "XXEncryptedProtocol_54504.h"
#import <UIKit/UIViewController.h>
#import "XXEncryptedProtocol_5452c.h"


__attribute__((visibility("hidden")))
@interface SearchResultViewController : UIViewController <XXEncryptedProtocol_5457c, XXEncryptedProtocol_544dc, XXEncryptedProtocol_54504, XXEncryptedProtocol_5452c, XXEncryptedProtocol_54554> {
@private
	? searchTextField;
	? searchFieldText;
	? searchFieldMode;
	? searchButton;
	? resultView;
	? footerView;
	? titleSearchButton;
	? nextSearchButton;
	? shouldShowFooterView;
	? searchQuery;
	? result;
	? request;
	? loadingView;
	? indicator;
	? autoCompleteView;
	? blockView;
	? autoCompleteDictionary;
	? scrollView;
	? styledTextView;
	? mailTitle;
	? mailBody;
	? observerRemoved;
	? wordbookAddAlert;
	? wordbookExistsAlert;
	? alert;
}
@property(assign) ? XXEncryptedProperty_40e38;
@property(assign) ? XXEncryptedProperty_40e12;
@property(assign) ? XXEncryptedProperty_40b9c;
@property(assign) ? XXEncryptedProperty_40de8;
@property(assign) ? XXEncryptedProperty_40db6;
@property(assign) ? XXEncryptedProperty_3df08;
@property(assign) ? XXEncryptedProperty_40b8c;
@property(assign) ? XXEncryptedProperty_40b80;
-(?)setMailBody:(?)body;
-(?)mailBody;
-(?)setMailTitle:(?)title;
-(?)mailTitle;
-(?)setAutoCompleteDictionary:(?)dictionary;
-(?)autoCompleteDictionary;
-(?)setSearchFieldMode:(?)mode;
-(?)searchFieldMode;
-(?)setSearchFieldText:(?)text;
-(?)searchFieldText;
-(?)setRequest:(?)request;
-(?)request;
-(?)setResult:(?)result;
-(?)result;
-(?)setSearchQuery:(?)query;
-(?)searchQuery;
-(?)applicationDidEnterBackground:(?)application;
-(?)tabBarControllerViewFrameChanged:(?)changed;
-(?)autoCompleteFailed:(?)failed;
-(?)autoCompleteSucceeded:(?)succeeded;
-(?)requestFailed:(?)failed;
-(?)loadSearchResult:(?)result;
-(?)requestFinished:(?)finished;
-(?)observeValueForKeyPath:(?)keyPath ofObject:(?)object change:(?)change context:(?)context;
-(?)blockViewTapped:(?)tapped;
-(?)keyboardWillHide:(?)keyboard;
-(?)keyboardDidShow:(?)keyboard;
-(?)keyboardWillShow:(?)keyboard;
-(?)nextSearchButtonPushed:(?)pushed;
-(?)titleSearchButtonPushed:(?)pushed;
-(?)backButtonPushed:(?)pushed;
-(?)searchButtonPushed:(?)pushed;
-(?)alertShowAnimationDidStop:(?)alertShowAnimation finished:(?)finished context:(?)context;
-(?)addWordbook:(?)wordbook;
-(?)sendMail:(?)mail;
-(?)alertView:(?)view clickedButtonAtIndex:(?)index;
-(?)mailComposeController:(?)controller didFinishWithResult:(?)result error:(?)error;
-(?)displayComposerSheet;
-(?)confirmLaunchMailApp;
-(?)textFieldShouldReturn:(?)textField;
-(?)textFieldDidEndEditing:(?)textField;
-(?)textFieldEditingChanged:(?)changed;
-(?)webView:(?)view didFailLoadWithError:(?)error;
-(?)webViewDidFinishLoad:(?)webView;
-(?)webView:(?)view shouldStartLoadWithRequest:(?)request navigationType:(?)type;
-(?)tableView:(?)view didSelectRowAtIndexPath:(?)indexPath;
-(?)tableView:(?)view cellForRowAtIndexPath:(?)indexPath;
-(?)tableView:(?)view numberOfRowsInSection:(?)section;
-(?)numberOfSectionsInTableView:(?)tableView;
-(?)setShowFooterView:(?)view;
-(?)viewDidUnload;
-(?)didReceiveMemoryWarning;
-(?)viewWillDisappear:(?)view;
-(?)viewWillAppear:(?)view;
-(?)viewDidLoad;
-(?)userDidTapView:(?)user;
-(?)loadView;
-(?)dealloc;
@end

