/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIButton.h>


__attribute__((visibility("hidden")))
@interface SearchModeView : UIButton {
@private
	? searchMode;
	? word;
	? title;
	? font;
	? color;
	? image;
	? highlightedImage;
}
@property(assign) ? XXEncryptedProperty_41040;
-(?)setSearchMode:(?)mode;
-(?)searchMode;
-(?)drawRect:(?)rect;
-(?)dealloc;
-(?)init;
@end

