/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface Settings : NSObject {
@private
	? version;
	? autoRotation;
	? showsRuby;
	? fontSize;
	? autoCompleteEnableChars;
	? autoComplete;
	? wordbook;
	? searchHistory;
}
@property(assign) ? XXEncryptedProperty_4130e;
@property(assign) ? XXEncryptedProperty_414c8;
@property(assign) ? XXEncryptedProperty_412f8;
@property(assign) ? XXEncryptedProperty_412e0;
@property(assign) ? XXEncryptedProperty_40044;
@property(assign) ? XXEncryptedProperty_41450;
@property(assign) ? XXEncryptedProperty_41430;
+(?)sharedInstance;
+(?)loadSettings;
-(?)setSearchHistory:(?)history;
-(?)searchHistory;
-(?)setWordbook:(?)wordbook;
-(?)wordbook;
-(?)setAutoComplete:(?)complete;
-(?)autoComplete;
-(?)setAutoCompleteEnableChars:(?)chars;
-(?)autoCompleteEnableChars;
-(?)setFontSize:(?)size;
-(?)fontSize;
-(?)setShowsRuby:(?)ruby;
-(?)showsRuby;
-(?)setAutoRotation:(?)rotation;
-(?)autoRotation;
-(?)dealloc;
-(?)encodeWithCoder:(?)coder;
-(?)initWithCoder:(?)coder;
-(?)init;
@end

