/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>


__attribute__((visibility("hidden")))
@interface TabBar : UIView {
@private
	? background;
	? searchButton;
	? wordbookButton;
	? historyButton;
	? settingButton;
	? tabBarController;
}
@property(assign) ? XXEncryptedProperty_3fa18;
-(?)setTabBarController:(?)controller;
-(?)tabBarController;
-(?)jumpToAboutView;
-(?)settingButtonPushed:(?)pushed;
-(?)historyButtonPushed:(?)pushed;
-(?)wordbookButtonPushed:(?)pushed;
-(?)searchButtonPushed:(?)pushed;
-(?)drawRect:(?)rect;
-(?)dealloc;
-(?)initWithFrame:(?)frame;
@end

