/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIButton.h>


__attribute__((visibility("hidden")))
@interface TabBarButton : UIButton {
@private
	? title;
	? titleFont;
	? selectedImage;
}
@property(assign) ? XXEncryptedProperty_3f080;
-(?)setTitle:(?)title;
-(?)title;
-(?)dealloc;
-(?)drawRect:(?)rect;
-(?)initWithFrame:(?)frame;
@end

