/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIWindow.h>


__attribute__((visibility("hidden")))
@interface TapDetectingWindow : UIWindow {
@private
	? viewToObserve;
	? controllerThatObserves;
}
@property(assign) ? XXEncryptedProperty_422b8;
@property(assign) ? XXEncryptedProperty_422aa;
-(?)setControllerThatObserves:(?)observes;
-(?)controllerThatObserves;
-(?)setViewToObserve:(?)observe;
-(?)viewToObserve;
-(?)sendEvent:(?)event;
-(?)forwardTap:(?)tap;
-(?)dealloc;
-(?)initWithViewToObserver:(?)observer andDelegate:(?)delegate;
@end

