/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_544dc.h"
#import "XXEncryptedProtocol_54504.h"
#import <UIKit/UIViewController.h>
#import "XXEncryptedProtocol_5452c.h"


__attribute__((visibility("hidden")))
@interface WordbookViewController : UIViewController <XXEncryptedProtocol_544dc, XXEncryptedProtocol_54504, XXEncryptedProtocol_5452c> {
@private
	? wordbookView;
}
-(?)tabBarControllerViewFrameChanged:(?)changed;
-(?)doneButtonPushed:(?)pushed;
-(?)editButtonPushed:(?)pushed;
-(?)tableView:(?)view canMoveRowAtIndexPath:(?)indexPath;
-(?)tableView:(?)view moveRowAtIndexPath:(?)indexPath toIndexPath:(?)indexPath3;
-(?)tableView:(?)view commitEditingStyle:(?)style forRowAtIndexPath:(?)indexPath;
-(?)tableView:(?)view canEditRowAtIndexPath:(?)indexPath;
-(?)tableView:(?)view didSelectRowAtIndexPath:(?)indexPath;
-(?)tableView:(?)view cellForRowAtIndexPath:(?)indexPath;
-(?)tableView:(?)view numberOfRowsInSection:(?)section;
-(?)numberOfSectionsInTableView:(?)tableView;
-(?)viewDidUnload;
-(?)didReceiveMemoryWarning;
-(?)viewWillDisappear:(?)view;
-(?)viewWillAppear:(?)view;
-(?)viewDidLoad;
-(?)loadView;
-(?)dealloc;
@end

