/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>


__attribute__((visibility("hidden")))
@interface WordCell : UITableViewCell {
@private
	? cellContentView;
	? title;
	? text;
}
@property(assign) ? XXEncryptedProperty_3d604;
@property(assign) ? XXEncryptedProperty_3f080;
-(?)setText:(?)text;
-(?)text;
-(?)setTitle:(?)title;
-(?)title;
-(?)setNeedsDisplay;
-(?)dealloc;
-(?)initWithStyle:(?)style reuseIdentifier:(?)identifier;
@end

