/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol XXEncryptedProtocol_54620
-(?)XXEncryptedMethod_44666;
@end

