/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_5443c.h"


@protocol XXEncryptedProtocol_54464 <XXEncryptedProtocol_5443c>
@optional
-(?)XXEncryptedMethod_3d1bb;
-(?)XXEncryptedMethod_3d18c;
-(?)XXEncryptedMethod_3d16c;
-(?)XXEncryptedMethod_41a34;
-(?)XXEncryptedMethod_3d134;
-(?)XXEncryptedMethod_3d10a;
-(?)XXEncryptedMethod_3d0cc;
-(?)XXEncryptedMethod_3d081;
-(?)XXEncryptedMethod_3d05c;
-(?)XXEncryptedMethod_3d00a;
-(?)XXEncryptedMethod_3cfd2;
-(?)XXEncryptedMethod_3cf8d;
-(?)XXEncryptedMethod_3cf6b;
-(?)XXEncryptedMethod_3cf51;
-(?)XXEncryptedMethod_3cf2d;
-(?)XXEncryptedMethod_3cee8;
-(?)XXEncryptedMethod_3cecd;
-(?)XXEncryptedMethod_3ceb0;
-(?)XXEncryptedMethod_3ce94;
-(?)XXEncryptedMethod_3ce5c;
-(?)XXEncryptedMethod_3ce33;
@end

