/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol XXEncryptedProtocol_545cc
@property(assign) ? XXEncryptedProperty_43126;
@property(assign) ? XXEncryptedProperty_43238;
-(?)XXEncryptedMethod_426be;
-(?)XXEncryptedMethod_43126;
-(?)XXEncryptedMethod_426ac;
-(?)XXEncryptedMethod_43238;
-(?)XXEncryptedMethod_4252c;
@end

