/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_5443c.h"


@protocol XXEncryptedProtocol_54658 <XXEncryptedProtocol_5443c>
@optional
-(?)XXEncryptedMethod_48cd4;
-(?)XXEncryptedMethod_45e80;
-(?)XXEncryptedMethod_45e6a;
-(?)XXEncryptedMethod_45e10;
-(?)XXEncryptedMethod_48ba6;
@end

