/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_5443c.h"


@protocol XXEncryptedProtocol_5457c <XXEncryptedProtocol_5443c>
@optional
-(?)XXEncryptedMethod_40785;
-(?)XXEncryptedMethod_4076f;
-(?)XXEncryptedMethod_41c78;
-(?)XXEncryptedMethod_40737;
@end

