/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_5443c.h"


@protocol XXEncryptedProtocol_54504 <XXEncryptedProtocol_5443c>
-(?)XXEncryptedMethod_43f20;
-(?)XXEncryptedMethod_41994;
@optional
-(?)XXEncryptedMethod_3de14;
-(?)XXEncryptedMethod_3ddd4;
-(?)XXEncryptedMethod_40a44;
-(?)XXEncryptedMethod_40a24;
-(?)XXEncryptedMethod_3dd94;
-(?)XXEncryptedMethod_40a02;
-(?)XXEncryptedMethod_3dd70;
-(?)XXEncryptedMethod_409dc;
-(?)XXEncryptedMethod_3dd46;
@end

