/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_544b4.h"
#import "XXEncryptedProtocol_5443c.h"


@protocol XXEncryptedProtocol_544dc <XXEncryptedProtocol_5443c, XXEncryptedProtocol_544b4>
@optional
-(?)XXEncryptedMethod_3db4e;
-(?)XXEncryptedMethod_3db06;
-(?)XXEncryptedMethod_3dadf;
-(?)XXEncryptedMethod_3dab5;
-(?)XXEncryptedMethod_3da76;
-(?)XXEncryptedMethod_3da39;
-(?)XXEncryptedMethod_3da10;
-(?)XXEncryptedMethod_3d9eb;
-(?)XXEncryptedMethod_40900;
-(?)XXEncryptedMethod_3d9c2;
-(?)XXEncryptedMethod_3d991;
-(?)XXEncryptedMethod_3d950;
-(?)XXEncryptedMethod_408bc;
-(?)XXEncryptedMethod_4089a;
-(?)XXEncryptedMethod_3d916;
-(?)XXEncryptedMethod_3d8f2;
-(?)XXEncryptedMethod_40866;
-(?)XXEncryptedMethod_40836;
-(?)XXEncryptedMethod_43e78;
@end

