/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_5443c.h"


@protocol XXEncryptedProtocol_5448c <XXEncryptedProtocol_5443c>
@optional
-(?)XXEncryptedMethod_3d32e;
-(?)XXEncryptedMethod_3d2e2;
-(?)XXEncryptedMethod_3d2ac;
-(?)XXEncryptedMethod_3d282;
-(?)XXEncryptedMethod_3d255;
@end

