/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol XXEncryptedProtocol_5443c
-(?)XXEncryptedMethod_3d240;
-(?)XXEncryptedMethod_407f8;
-(?)XXEncryptedMethod_3cd40;
-(?)XXEncryptedMethod_44270;
-(?)XXEncryptedMethod_41270;
-(?)XXEncryptedMethod_3dc00;
-(?)XXEncryptedMethod_3dbec;
-(?)XXEncryptedMethod_43e60;
-(?)XXEncryptedMethod_3d230;
-(?)XXEncryptedMethod_43e48;
-(?)XXEncryptedMethod_3dbbc;
-(?)XXEncryptedMethod_43e08;
-(?)XXEncryptedMethod_42460;
-(?)XXEncryptedMethod_3d220;
-(?)XXEncryptedMethod_49890;
-(?)XXEncryptedMethod_3dbb0;
-(?)XXEncryptedMethod_3d20c;
-(?)XXEncryptedMethod_3d200;
-(?)XXEncryptedMethod_3efa8;
@end

