/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_5443c.h"


@protocol XXEncryptedProtocol_5452c <XXEncryptedProtocol_5443c>
@optional
-(?)XXEncryptedMethod_3fada;
-(?)XXEncryptedMethod_40ad4;
-(?)XXEncryptedMethod_3de7e;
-(?)XXEncryptedMethod_3de66;
-(?)XXEncryptedMethod_40a9a;
-(?)XXEncryptedMethod_40a80;
-(?)XXEncryptedMethod_3de44;
@end

