/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_5443c.h"


@protocol XXEncryptedProtocol_546a8 <XXEncryptedProtocol_5443c>
-(?)XXEncryptedMethod_46d4e;
-(?)XXEncryptedMethod_49554;
-(?)XXEncryptedMethod_49850;
-(?)XXEncryptedMethod_495a8;
-(?)XXEncryptedMethod_4693a;
-(?)XXEncryptedMethod_49824;
-(?)XXEncryptedMethod_46984;
-(?)XXEncryptedMethod_451b2;
@end

