/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_5443c.h"


@protocol XXEncryptedProtocol_545f8 <XXEncryptedProtocol_5443c>
@optional
-(?)XXEncryptedMethod_43d9d;
-(?)XXEncryptedMethod_43d75;
-(?)XXEncryptedMethod_43d5e;
-(?)XXEncryptedMethod_43d46;
-(?)XXEncryptedMethod_43d33;
-(?)XXEncryptedMethod_43d04;
@end

