/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_5443c.h"


@protocol XXEncryptedProtocol_54680 <XXEncryptedProtocol_5443c>
@optional
-(?)XXEncryptedMethod_46528;
-(?)XXEncryptedMethod_48e38;
-(?)XXEncryptedMethod_44bc3;
-(?)XXEncryptedMethod_3e908;
-(?)XXEncryptedMethod_40b60;
-(?)XXEncryptedMethod_44830;
-(?)XXEncryptedMethod_44820;
@end

