/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_5443c.h"


@protocol XXEncryptedProtocol_54554 <XXEncryptedProtocol_5443c>
@optional
-(?)XXEncryptedMethod_3e7b6;
@end

