/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XXEncryptedProtocol_5443c.h"


@protocol XXEncryptedProtocol_544b4 <XXEncryptedProtocol_5443c>
@optional
-(?)XXEncryptedMethod_3dd08;
-(?)XXEncryptedMethod_409aa;
-(?)XXEncryptedMethod_40970;
-(?)XXEncryptedMethod_3dcdc;
-(?)XXEncryptedMethod_3dcb6;
-(?)XXEncryptedMethod_3dc92;
-(?)XXEncryptedMethod_3dc74;
-(?)XXEncryptedMethod_40942;
-(?)XXEncryptedMethod_43ee8;
-(?)XXEncryptedMethod_3dc40;
-(?)XXEncryptedMethod_43ec8;
-(?)XXEncryptedMethod_3dc1e;
@end

